import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { SESSION_COOKIE, SESSION_TAG, SESSION_TTL_SECONDS } from "@/lib/session-cookie";
import type { Principal } from "@/lib/rbac";
import { countUsers, findUserById, toPrincipal, type UserRow } from "@/lib/users";

/**
 * Sessions and the identity behind them.
 *
 * Starkvisionz holds a project's cost, schedule and commercial position, so who is
 * asking decides what comes back. Accounts are local — see `src/lib/users.ts` —
 * and this module turns a signed cookie back into the account that holds it.
 *
 * Design notes:
 * - The cookie is a signed, expiring bearer with no server-side session store
 *   to lose on restart. It carries the account id and the account's
 *   `session_version`, so revocation is a column bump rather than a table of
 *   live sessions: change a password, a role or a project grant and every
 *   cookie already issued stops verifying.
 * - The edge middleware checks the signature and the expiry only, because it
 *   cannot reach the database. Node routes re-resolve the account on every
 *   request, which is where deactivation and version checks actually bite.
 * - Comparisons are constant-time; a timing oracle on the signature would
 *   defeat the point.
 * - Production without a session secret fails CLOSED. An unauthenticated
 *   controls system on the public internet is the failure this exists to stop,
 *   so it must never be what a missing variable produces.
 */

export { SESSION_COOKIE };

export type AuthMode =
  | { kind: "enforced"; secret: string }
  /** Local development with no secret set: open, and the UI says so. */
  | { kind: "open"; reason: string }
  /** Production with no secret set: refuse to serve rather than serve nude. */
  | { kind: "misconfigured"; reason: string };

function envValue(name: string): string | undefined {
  const value = process.env[name];
  return value && value.trim() ? value.trim() : undefined;
}

/**
 * Resolves how the app should behave given the current configuration. Called on
 * every request so a deployment cannot be left in a state the operator believes
 * is protected but is not.
 */
export function authMode(): AuthMode {
  const secret = envValue("STARKVISIONZ_SESSION_SECRET");
  if (secret) return { kind: "enforced", secret };

  return process.env.NODE_ENV === "production"
    ? {
        kind: "misconfigured",
        reason:
          "STARKVISIONZ_SESSION_SECRET is not set. Starkvisionz will not serve project data " +
          "unauthenticated in production.",
      }
    : {
        kind: "open",
        reason:
          "STARKVISIONZ_SESSION_SECRET is not set — running as a local development " +
          "administrator with access control switched off.",
      };
}

export function isAuthEnforced(): boolean {
  return authMode().kind === "enforced";
}

/**
 * The identity used when the app is running open for local development.
 *
 * It is an administrator so that `npm run dev` works with no configuration, and
 * it is flagged so every surface that shows who you are can say plainly that
 * nothing is being enforced.
 */
export const DEVELOPMENT_PRINCIPAL: Principal = {
  id: "development",
  email: "development@localhost",
  name: "Local development",
  role: "admin",
  grants: [],
  development: true,
};

// ---------------------------------------------------------------------------
// Session token
// ---------------------------------------------------------------------------

/** Length-safe constant-time comparison. */
function safeEqual(a: string, b: string): boolean {
  const left = Buffer.from(a, "utf8");
  const right = Buffer.from(b, "utf8");
  if (left.length !== right.length) {
    // Still compare, so a wrong length costs the same as a wrong value.
    timingSafeEqual(left, left);
    return false;
  }
  return timingSafeEqual(left, right);
}

function sign(payload: string, secret: string): string {
  return createHmac("sha256", secret).update(payload).digest("base64url");
}

/** `v2.<userId>.<sessionVersion>.<issuedAt>.<expiresAt>.<signature>` */
export { SESSION_TAG as SESSION_VERSION_TAG };

export type SessionClaims = { userId: string; sessionVersion: number; expiresAt: number };

export function issueSession(user: UserRow, secret: string, now = Date.now()): string {
  const issued = Math.floor(now / 1000);
  const expires = issued + SESSION_TTL_SECONDS;
  // The id is generated by `createUser` and never contains a separator; a
  // hand-edited row that did would produce a token that cannot be parsed back,
  // which fails closed.
  const payload = `${SESSION_TAG}.${user.id}.${user.session_version}.${issued}.${expires}`;
  return `${payload}.${sign(payload, secret)}`;
}

/** Verifies signature and expiry. Says nothing about whether the account still exists. */
export function readSession(
  token: string | undefined,
  secret: string,
  now = Date.now()
): SessionClaims | null {
  if (!token) return null;

  const parts = token.split(".");
  if (parts.length !== 6 || parts[0] !== SESSION_TAG) return null;

  const [, userId, version, issued, expires, signature] = parts;
  const payload = `${SESSION_TAG}.${userId}.${version}.${issued}.${expires}`;
  if (!safeEqual(signature, sign(payload, secret))) return null;

  const expiresAt = Number(expires);
  const sessionVersion = Number(version);
  if (!Number.isFinite(expiresAt) || !Number.isInteger(sessionVersion)) return null;
  if (expiresAt * 1000 <= now) return null;

  return { userId, sessionVersion, expiresAt };
}

// ---------------------------------------------------------------------------
// Request -> principal
// ---------------------------------------------------------------------------

function cookieFromRequest(req: Request, name: string): string | undefined {
  const header = req.headers.get("cookie");
  if (!header) return undefined;
  for (const part of header.split(";")) {
    const [key, ...rest] = part.trim().split("=");
    if (key === name) return rest.join("=");
  }
  return undefined;
}

export type Resolution =
  | { ok: true; principal: Principal }
  | { ok: false; status: 401 | 503; reason: string };

/**
 * Turns a request into the account making it.
 *
 * This is the check that matters. The middleware has already refused anything
 * without a well-formed cookie, but it could not know whether the account was
 * since deactivated, demoted or re-scoped — so every route asks here, and the
 * answer comes from the current row rather than from the token.
 */
export function resolvePrincipal(req: Request): Resolution {
  return resolveSessionToken(cookieFromRequest(req, SESSION_COOKIE));
}

/**
 * The same resolution from a raw cookie value, for server components that read
 * `cookies()` rather than holding a Request.
 */
export function resolveSessionToken(token: string | undefined): Resolution {
  const mode = authMode();

  if (mode.kind === "misconfigured") return { ok: false, status: 503, reason: mode.reason };
  if (mode.kind === "open") return { ok: true, principal: DEVELOPMENT_PRINCIPAL };

  const claims = readSession(token, mode.secret);
  if (!claims) return { ok: false, status: 401, reason: "Authentication required" };

  const user = findUserById(claims.userId);
  if (!user || user.is_active !== 1) {
    return { ok: false, status: 401, reason: "This account is no longer active." };
  }
  if (user.session_version !== claims.sessionVersion) {
    return {
      ok: false,
      status: 401,
      reason: "Your access changed, so this session ended. Sign in again.",
    };
  }

  return { ok: true, principal: toPrincipal(user) };
}

/** Whether an operator still has to create the first account. */
export function needsBootstrap(): boolean {
  return authMode().kind === "enforced" && countUsers() === 0;
}

export const sessionCookieOptions = {
  httpOnly: true,
  sameSite: "lax" as const,
  path: "/",
  maxAge: SESSION_TTL_SECONDS,
  // Set on HTTPS deployments; left off locally so login works over plain http.
  secure: process.env.NODE_ENV === "production",
};

/** Used by `npm run auth:secret` to print a signing key. */
export function generateSecret(): string {
  return randomBytes(32).toString("hex");
}
